"""Add TPP table

Revision ID: 27861588d5c9
Revises: a2a1581db7af
Create Date: 2026-05-14 11:46:10.300338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27861588d5c9'
down_revision: Union[str, Sequence[str], None] = 'a2a1581db7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['persona.brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_tpp_brand_id'), 'tpp', ['brand_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_tpp_id'), 'tpp', ['id'], unique=False, schema='persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_tpp_id'), table_name='tpp', schema='persona')
    op.drop_index(op.f('ix_persona_tpp_brand_id'), table_name='tpp', schema='persona')
    op.drop_table('tpp', schema='persona')
    # ### end Alembic commands ###
