"""Add EmotionAggregate table

Revision ID: 4f1da3463e3c
Revises: 
Create Date: 2026-05-15 11:23:46.092698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1da3463e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uuid', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_emotion_aggregate_id'), 'emotion_aggregate', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_emotion_aggregate_image_uuid'), 'emotion_aggregate', ['image_uuid'], unique=False, schema='persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_emotion_aggregate_image_uuid'), table_name='emotion_aggregate', schema='persona')
    op.drop_index(op.f('ix_persona_emotion_aggregate_id'), table_name='emotion_aggregate', schema='persona')
    op.drop_table('emotion_aggregate', schema='persona')
    # ### end Alembic commands ###
