"""Initial schema

Revision ID: 7c4452efdfdd
Revises: 
Create Date: 2026-04-21 11:13:11.928313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4452efdfdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('vector_store_id', sa.String(), nullable=True),
    sa.Column('extracted_insights', sa.JSON(), nullable=True),
    sa.Column('gemini_document_name', sa.String(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_brand_documents_brand_id'), 'brand_documents', ['brand_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_brand_documents_id'), 'brand_documents', ['id'], unique=False, schema='persona')
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_brands_id'), 'brands', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_brands_name'), 'brands', ['name'], unique=True, schema='persona')
    op.create_table('cached_asset_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('persona_hash', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_cached_asset_analysis_id'), 'cached_asset_analysis', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_cached_asset_analysis_image_hash'), 'cached_asset_analysis', ['image_hash'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_cached_asset_analysis_persona_hash'), 'cached_asset_analysis', ['persona_hash'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_cached_asset_analysis_persona_id'), 'cached_asset_analysis', ['persona_id'], unique=False, schema='persona')
    op.create_table('saved_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('simulation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_saved_simulations_id'), 'saved_simulations', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_saved_simulations_name'), 'saved_simulations', ['name'], unique=True, schema='persona')
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_simulations_id'), 'simulations', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_simulations_persona_id'), 'simulations', ['persona_id'], unique=False, schema='persona')
    op.create_table('synthetic_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('persona_ids', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_synthetic_test_runs_id'), 'synthetic_test_runs', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_synthetic_test_runs_name'), 'synthetic_test_runs', ['name'], unique=False, schema='persona')
    op.create_table('task_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('response_stored', sa.JSON(), nullable=True),
    sa.Column('type_test', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('task_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_task_history_id'), 'task_history', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_task_history_task_id'), 'task_history', ['task_id'], unique=False, schema='persona')
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('journey_stage', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_by_user', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['persona.brands.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['persona.brand_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_knowledge_nodes_brand_id'), 'knowledge_nodes', ['brand_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_knowledge_nodes_node_type'), 'knowledge_nodes', ['node_type'], unique=False, schema='persona')
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('persona_type', sa.String(), nullable=True),
    sa.Column('persona_subtype', sa.String(), nullable=True),
    sa.Column('disease_pack', sa.String(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('practice_setup', sa.Text(), nullable=True),
    sa.Column('system_context', sa.Text(), nullable=True),
    sa.Column('decision_influencers', sa.Text(), nullable=True),
    sa.Column('adherence_to_protocols', sa.String(), nullable=True),
    sa.Column('channel_use', sa.Text(), nullable=True),
    sa.Column('decision_style', sa.String(), nullable=True),
    sa.Column('core_insight', sa.Text(), nullable=True),
    sa.Column('additional_context', sa.JSON(), nullable=True),
    sa.Column('full_persona_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['persona.brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_personas_brand_id'), 'personas', ['brand_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_personas_id'), 'personas', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_personas_name'), 'personas', ['name'], unique=False, schema='persona')
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['persona.brands.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_chat_sessions_id'), 'chat_sessions', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_chat_sessions_persona_id'), 'chat_sessions', ['persona_id'], unique=False, schema='persona')
    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('from_node_id', sa.String(), nullable=True),
    sa.Column('to_node_id', sa.String(), nullable=True),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('inferred_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['persona.brands.id'], ),
    sa.ForeignKeyConstraint(['from_node_id'], ['persona.knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['persona.knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_knowledge_relations_brand_id'), 'knowledge_relations', ['brand_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_knowledge_relations_from_node_id'), 'knowledge_relations', ['from_node_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_knowledge_relations_id'), 'knowledge_relations', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_knowledge_relations_to_node_id'), 'knowledge_relations', ['to_node_id'], unique=False, schema='persona')
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('thought_process', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['persona.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_chat_messages_id'), 'chat_messages', ['id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_chat_messages_session_id'), table_name='chat_messages', schema='persona')
    op.drop_index(op.f('ix_persona_chat_messages_id'), table_name='chat_messages', schema='persona')
    op.drop_table('chat_messages', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_relations_to_node_id'), table_name='knowledge_relations', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_relations_id'), table_name='knowledge_relations', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_relations_from_node_id'), table_name='knowledge_relations', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_relations_brand_id'), table_name='knowledge_relations', schema='persona')
    op.drop_table('knowledge_relations', schema='persona')
    op.drop_index(op.f('ix_persona_chat_sessions_persona_id'), table_name='chat_sessions', schema='persona')
    op.drop_index(op.f('ix_persona_chat_sessions_id'), table_name='chat_sessions', schema='persona')
    op.drop_table('chat_sessions', schema='persona')
    op.drop_index(op.f('ix_persona_personas_name'), table_name='personas', schema='persona')
    op.drop_index(op.f('ix_persona_personas_id'), table_name='personas', schema='persona')
    op.drop_index(op.f('ix_persona_personas_brand_id'), table_name='personas', schema='persona')
    op.drop_table('personas', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_nodes_node_type'), table_name='knowledge_nodes', schema='persona')
    op.drop_index(op.f('ix_persona_knowledge_nodes_brand_id'), table_name='knowledge_nodes', schema='persona')
    op.drop_table('knowledge_nodes', schema='persona')
    op.drop_index(op.f('ix_persona_task_history_task_id'), table_name='task_history', schema='persona')
    op.drop_index(op.f('ix_persona_task_history_id'), table_name='task_history', schema='persona')
    op.drop_table('task_history', schema='persona')
    op.drop_index(op.f('ix_persona_synthetic_test_runs_name'), table_name='synthetic_test_runs', schema='persona')
    op.drop_index(op.f('ix_persona_synthetic_test_runs_id'), table_name='synthetic_test_runs', schema='persona')
    op.drop_table('synthetic_test_runs', schema='persona')
    op.drop_index(op.f('ix_persona_simulations_persona_id'), table_name='simulations', schema='persona')
    op.drop_index(op.f('ix_persona_simulations_id'), table_name='simulations', schema='persona')
    op.drop_table('simulations', schema='persona')
    op.drop_index(op.f('ix_persona_saved_simulations_name'), table_name='saved_simulations', schema='persona')
    op.drop_index(op.f('ix_persona_saved_simulations_id'), table_name='saved_simulations', schema='persona')
    op.drop_table('saved_simulations', schema='persona')
    op.drop_index(op.f('ix_persona_cached_asset_analysis_persona_id'), table_name='cached_asset_analysis', schema='persona')
    op.drop_index(op.f('ix_persona_cached_asset_analysis_persona_hash'), table_name='cached_asset_analysis', schema='persona')
    op.drop_index(op.f('ix_persona_cached_asset_analysis_image_hash'), table_name='cached_asset_analysis', schema='persona')
    op.drop_index(op.f('ix_persona_cached_asset_analysis_id'), table_name='cached_asset_analysis', schema='persona')
    op.drop_table('cached_asset_analysis', schema='persona')
    op.drop_index(op.f('ix_persona_brands_name'), table_name='brands', schema='persona')
    op.drop_index(op.f('ix_persona_brands_id'), table_name='brands', schema='persona')
    op.drop_table('brands', schema='persona')
    op.drop_index(op.f('ix_persona_brand_documents_id'), table_name='brand_documents', schema='persona')
    op.drop_index(op.f('ix_persona_brand_documents_brand_id'), table_name='brand_documents', schema='persona')
    op.drop_table('brand_documents', schema='persona')
    # ### end Alembic commands ###
