"""Add Campaign and ConceptImage tables

Revision ID: a2a1581db7af
Revises: 7c4452efdfdd
Create Date: 2026-05-13 17:28:45.995741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a1581db7af'
down_revision: Union[str, Sequence[str], None] = '7c4452efdfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response_received', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_campaigns_id'), 'campaigns', ['id'], unique=False, schema='persona')
    op.create_table('concept_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('image_descriptor', sa.Text(), nullable=True),
    sa.Column('image_url_str', sa.Text(), nullable=True),
    sa.Column('thumbnail_url_str', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='persona'
    )
    op.create_index(op.f('ix_persona_concept_images_campaign_id'), 'concept_images', ['campaign_id'], unique=False, schema='persona')
    op.create_index(op.f('ix_persona_concept_images_id'), 'concept_images', ['id'], unique=False, schema='persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_concept_images_id'), table_name='concept_images', schema='persona')
    op.drop_index(op.f('ix_persona_concept_images_campaign_id'), table_name='concept_images', schema='persona')
    op.drop_table('concept_images', schema='persona')
    op.drop_index(op.f('ix_persona_campaigns_id'), table_name='campaigns', schema='persona')
    op.drop_index(op.f('ix_persona_campaigns_campaign_id'), table_name='campaigns', schema='persona')
    op.drop_table('campaigns', schema='persona')
    # ### end Alembic commands ###
